### ISSUE TITLE
Add new options under Settings > Customizer

### ISSUE THREAD

**Issue by nickburne** [PootlePress/customizer-customizer#2]
Under settings customizer add checkbox options to display each option section of the WP Customizer.

Each checkbox should be default enabled. So for example if Menu Customizer was activated it would list:
- Primary Nav Container
- Menu Items
- Sub menu
- Call to action button

each with a checkbox to display it in the WP Customizer.

**Comment by nickburne** [comment]
Please use the customizer api...

**Comment by nickburne** [comment]
To be clear it should list ALL the option sections from the WP Customizer. For some sites this would be a very long list...

**Comment by nickburne** [comment]
How is this going?

**Comment by zero0000zero** [comment]
This is in progress...

**Comment by zero0000zero** [comment]
I am testing Customizer Customizer on demo. It reports an error that should not occur in WP Core...
Can you restart demo server? That may solve the error.

**Comment by nickburne** [comment]
Ok - I will get Jamie to restart. 

For now, can you commit and we will test on local host...

Thanks!

**Comment by zero0000zero** [comment]
It is committed now!.

**Comment by nickburne** [comment]
Ok - closing this and will add new tickets.
