### ISSUE TITLE
Get error message when try and change an option

### ISSUE THREAD

**Issue by nickburne** [PootlePress/customizer-customizer#3]
If I try and change any of the options I get this message:

Fatal error: Cannot redeclare class WP_Customize_Filter_Setting in /Applications/AMPPS/www/storefront/wp-includes/class-wp-customize-setting.php on line 513

**Comment by zero0000zero** [comment]
This is the same error as in demo. I found the cause and fixed it. WP core doesn't make using customizer classes easy. Tested on demo and committe to GitHub!

**Comment by nickburne** [comment]
Fixed!
