### ISSUE TITLE
Order of options

### ISSUE THREAD

**Issue by nickburne** [PootlePress/customizer-customizer#6]
Hey Alan - how is the plugin pulling in the order of the options? (from top to bottom)

Would be so much easier to use if it was in the same order as the Customizer itself...

**Comment by zero0000zero** [comment]
The order is from what the customizer api returns when the plugin uses the api.

**Comment by nickburne** [comment]
Hi Alan,

I would really like it ordered in the same order as the WP Customizer. Can you try and find a solution?

Thanks!

Nick

**Comment by zero0000zero** [comment]
Now it will follow the order as specified in the priority of sections (that was passed to customizer when adding sections). I tested on demo and committed to GitHub.

**Comment by nickburne** [comment]
Great work.
