### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by nickburne** [PootlePress/customizer-customizer#8]
People getting this error message when using the plugin:

Parse error: syntax error, unexpected T_FUNCTION in /home1/qcollege/public_html/dougansfarm/wp-content/plugins/hide-wp-customizer-options/classes/class-pp-customizer-customizer-settings.php on line 305

**Comment by zero0000zero** [comment]
The plugin uses a PHP feature that is available after 5.3 . Those people have older PHP version.
The part is replaced with other code. Tested on demo and committed to GitHub.
